### ISSUE TITLE
FR: Option to remove row numbers

### ISSUE THREAD

**Issue by iantrich** [tuanha2000vn/hasskit#1]

**Comment by tuanha2000vn** [comment]
NO :D

**Comment by tuanha2000vn** [comment]
May make an option to make UI event cleaner. Default is show to make new user less confusing about [1] [2] [3] [4]

**Comment by skynet01** [comment]
Yeah they can be just line separators.

**Comment by tuanha2000vn** [comment]
I'll come back when we can find a nice looking solution.

**Comment by tuanha2000vn** [comment]
![Screenshot_1574927239](https://user-images.githubusercontent.com/2765517/69786967-1034b600-11ee-11ea-9cbd-63493f9eea1f.png)

Not removed but make it very very thin. Consider it's closed.
