### ISSUE TITLE
FR: display attribute

### ISSUE THREAD

**Issue by iantrich** [tuanha2000vn/hasskit#14]
option to display an attribute in the top right

e.g. light brightness, battery level

would be something you would set from the detail screen of an entity

**Comment by iantrich** [comment]
general idea from button-card
![image](https://user-images.githubusercontent.com/1287159/69673200-69baaa80-105f-11ea-9a21-04f114611567.png)

**Comment by tuanha2000vn** [comment]
maybe not, the UI is getting messy and have a lot detail already.  maybe later click on each entity will show it detail.

And hurry up with the flutter installation, the fun have just began.
