### ISSUE TITLE
FR: device_tracker map detail

### ISSUE THREAD

**Issue by iantrich** [tuanha2000vn/hasskit#15]
Show the location of a device_tracker on a map when the detail is brought up

**Comment by tuanha2000vn** [comment]
Ok, let me learn how to use it. I never actually use it on my Hass, was using Find my iPhone.

**Comment by tuanha2000vn** [comment]
Finally made it :D

https://cdn.discordapp.com/attachments/632793649012539445/659762376031207443/untitled_2.gif
