### ISSUE TITLE
FR: weather detail

### ISSUE THREAD

**Issue by iantrich** [tuanha2000vn/hasskit#16]
Show the current weather details on a `weather` entity. Doing a forecast would be great too (you can have hourly or daily weather entities), but at the least the current conditions for an MVP

**Comment by iantrich** [comment]
e.g.
![image](https://user-images.githubusercontent.com/1287159/69672723-4fcc9800-105e-11ea-886b-ed2c877dd897.png)

**Comment by iantrich** [comment]
![image](https://user-images.githubusercontent.com/1287159/69672807-7b4f8280-105e-11ea-9fe2-b36616ca54e4.png)

**Comment by tuanha2000vn** [comment]
I'm not sure it's really needed because on Phone there's are a tone of weather app...

**Comment by iantrich** [comment]
Well I have apps for all my current HA things as well. But yeah, this is a "nice to have" feature. If I ever get my setup working I'll likely implement this 😜

**Comment by tuanha2000vn** [comment]
![Screenshot_1575350553](https://user-images.githubusercontent.com/2765517/70022678-9b83c200-15c7-11ea-8e44-c4e2ef2968ea.png)

Version 3.0 add webview support, consider this as closed
