### ISSUE TITLE
Alarm panel - modes 

### ISSUE THREAD

**Issue by Tyre88** [tuanha2000vn/hasskit#18]
Add arm home and arm away

**Comment by Tyre88** [comment]
![image](https://user-images.githubusercontent.com/4730856/69716206-e3a76e00-1109-11ea-9009-818851e1f0b5.png)

**Comment by Tyre88** [comment]
Looks good? Or should we have other icons? @tuanha2000vn

**Comment by tuanha2000vn** [comment]
![untitled](https://user-images.githubusercontent.com/2765517/69727653-8df8b300-1155-11ea-9ca4-0d4dafec0e4c.gif)

Final version, thank Tyre88
