### ISSUE TITLE
UI label glitch

### ISSUE THREAD

**Issue by A320Peter** [tuanha2000vn/hasskit#35]
In 3 and 4 buttons mode some state labels are broken in English. iPhone X.

Would it be possible to optionally choose between the rounded and square shaped buttons? I really liked the 'Apple Home' styled buttons.

![IMG_7509](https://user-images.githubusercontent.com/14132653/70617086-1d9b6880-1c10-11ea-9521-029e28c42097.jpg)

**Comment by tuanha2000vn** [comment]
Currently it's not possible with what I know, I'll find solution.

**Comment by tuanha2000vn** [comment]
![Screenshot_1576144647](https://user-images.githubusercontent.com/2765517/70702350-819d5a00-1d00-11ea-94ac-93141b22534d.png)

New layout will fix the issue
