### ISSUE TITLE
Offer contribution

### ISSUE THREAD

**Issue by markus-fischbacher** [tuanha2000vn/hasskit#39]
Hi there,
I've created German translations that I can push to a new branch if desired.

Regards,
Markus

**Comment by markus-fischbacher** [comment]
Tried to build the project. Need guidance with creating GoogleService-Info.plist please.

**Comment by tuanha2000vn** [comment]
Thank, please sent the lang file for make a pull request.

You can make your own firestore database, guide here:
https://firebase.google.com/docs/flutter/setup

**Comment by tuanha2000vn** [comment]
If you still have issue setting up the project, please contact me on discord https://discord.gg/cqYr52P

**Comment by steckenpferd** [comment]
I also created a German translation here:
https://github.com/tuanha2000vn/hasskit/pull/40

**Comment by markus-fischbacher** [comment]
> I also created a German translation here:
> #40

Hab mir deine Übersetzungen angeschaut. Manches habe ich anders verstanden. Vielleicht sollten wir unsere Versionen vergleichen und einen Konsens finden.

#41

**Comment by steckenpferd** [comment]
Gute Idee

**Comment by steckenpferd** [comment]
Hi,

da meins durch ist kann man es absofort jederzeit per Pull Request anpassen. 
Ich habe mir mal die Unterschiede angeschaut - hier meine Vorschläge.

**Passt meiner Meinung muss nicht geändert werden:**
"on": Ich: An vs Du: "Ein"
"reset": "Reset" vs Du: "Zurücksetzen"
"rbg_color":  Ich:  "Lange drücken um Farbe zu ändern", vs Du: "Lange drücken um die Farbe zu wählen"
"edit": Ich: "Editieren" vs Du:  "Bearbeiten"
"add_room": Ich "Raum hinzufügen" vs Du: "Neuen Raum hinzufügen"
"pick_color": Ich: "Wähle eine Farbe!" vs Du: "Farbe wählen!"
"connecting": Ich:  "Verbinde mit", vs Du: "Verbinden zu",
new_connection": Ich: "Erstelle neue Verbindung...", vs Du:  "Neue Verbindung erstellen..."
use_https": Ich: "Nutze https", vs Du: "https verwenden"
"sync": Ich: "Synchronisiere mit Google Cloud" vs Du: "Google Cloud Sync",
"theme_color": Ich: "Themen Farbe", vs Du: "Schema Farbe",
"force_reset": Ich: "Erzwinge einen Reset der Daten auf der Cloud" vs Du: "Zurücksetzen der Daten in der Cloud erzwingen"
"dark": Ich: "Dunkel", - Du: "Dunkles Schema", - nennt es auch Apple so
"light": Ich: "Hell" - Du: "Helles Schema"
"on": Ich: "An", vs Du: "Ein"
"locked": Ich: "Gesperrt", vs Du: "Abgesperrt",
"locking": Ich: "Sperren...", vs Du: "Absperren...",
"unlocked": Ich: "Entsperrt", vs Du: "Aufgesperrt",
"unlocking": Ich: "Entsperren...", vs Du: "Aufsperren...",
komplett "fan..."


**Find ich sinnvoll und ändere es sofort per Pull Request:**
last_update": Ich: "Neustes Update" vs Du: "Letztes Update"
"cancel":  Ich "Annulieren" vs Du: "Abbrechen"
"rooms": Ich: "Raum" vs Du: "Räume" - das ich ein echter Fehler von mir
"last_access":  Ich: "Letzter Zugang" vs Du: "Letzter Zugriff",
"select_icon": Ich: "Wähle angepasstes Icon", vs Du: "Benutzerdefiniertes Icon wählen",
"reset_icon": Ich: "Resete Icon" vs Du: "Icon zurücksetzen",
"arrange": Ich: "Ordnen" vs Du: "Anordnen"
"move": Ich: "Bewegen" vs : " "Verschieben",
 "1_touch": Ich: "Kann jetzt mit 1x Touch geöffnet werden" vs Ich NEU: "Kann per 1x antippen geöffnet werden"
"saved": Ich: "Website sichern", vs Du: "Webseite speichern"
"reload": "Website erneut laden",
"pin": "Website anheften - verhindert Website scrollen",
"unpin": "Website anheften aufheben - erlaubt Website scrollen",
"y_weather": "Y! Weather",
"aspect": "Aspect"
"correct_info": Ich: "Versichere dich das folgende Informationen korrekt sind" vs Du: Bitte sicherstellen, dass die nachfolgenden Informationen richtig sind",
"cancel": "Web Login Verbindung abbrechen"
about": "Über HassKit",
"about_info" - überarbeite ich nochmal
"settingLocked": "Serververbindung, Cloud Sync und Raumeinstellungen sperren"
"use": "Cloud Daten Synchronisation verwenden",
 "info":  - passe ich an
"sync_problem" - passe ich an
"force_upload": - passe ich an


**Zur Diskussion:**
"no_data": Ich: "stellt keine Daten zur Verfügung" vs Du: "keine Daten verfügbar"
"connect_hass": Ich: "Verbinde dich mit Home Assistant" vs "Bitte eine Verbindung zum\nHome Assistant herstellen",
komplett Ich: Schutz vs Du: Scharf - finde meins besser bis auf "Pending" - ist das gleichzusetzen wie "in Progress" ??
Hier habe ich mich an die englische Fassung gehalten:
"require_slide_open_disabled": Ich: "Schiebeleiste betätigen um deaktivieren zu öffnen", vs Du:  "Schieben um deaktiviert zu öffnen",
"require_slide_open_enabled": Ich: "Schiebeleiste betätigen um aktivieren zu öffnen", vs Du: "Schieben um aktiviert zu öffnen",
 "prevent_accidentally_open": Ich: "Verhindere ungewolltes öffnen", vs Du: "Versehentliches Öffnen verhindern",
"3_buttons": Ich: "3 Knöpfe", vs Du: "3 Buttons",
"4_buttons": Ich: "4 Knöpfe" vs Du: "4 Buttons",

**Comment by steckenpferd** [comment]
Pull Request mit den sinnvollen Änderungen erstellt: https://github.com/tuanha2000vn/hasskit/pull/42

**Comment by steckenpferd** [comment]
Hab Hasskit gerade neben iOS noch zusätzlich auf Android installiert - da kann man die Sprache bereits testen - sehe das sobald Pull Request 42 genehmigt ist ich noch einen weiteren erstellen muss.

**Comment by steckenpferd** [comment]
Noch einen Mini Pull Request erstellt: https://github.com/tuanha2000vn/hasskit/pull/43

**Comment by tuanha2000vn** [comment]
Thank, appreciate your contribution.

Vielen Dank für Ihren Beitrag.

**Comment by markus-fischbacher** [comment]
@steckenpferd finde ich gut 👍🏻
Mir fehlte sicher bei einigen Texten der Kontext in der App.
