### ISSUE TITLE
FR:  status display option (below name OR next to icon)

### ISSUE THREAD

**Issue by WhistleMaster** [tuanha2000vn/hasskit#4]
Hi ! 

Thanks for the great work on this app, really cool !

Would it be possible to have the option to choose where to display an entity status:

next to the icon:
<img width="142" alt="Screenshot 2019-11-21 at 10 40 49" src="https://user-images.githubusercontent.com/1544568/69326082-8152f700-0c4b-11ea-9554-d4feaf6d22ba.png">

OR 

below the name:
<img width="140" alt="Screenshot 2019-11-21 at 10 40 46" src="https://user-images.githubusercontent.com/1544568/69326098-8617ab00-0c4b-11ea-88fb-d2d0457092ad.png">

That would be nice for some entities such as device_tracker or input_select with long status text:
<img width="141" alt="Screenshot 2019-11-21 at 10 41 05" src="https://user-images.githubusercontent.com/1544568/69326180-ac3d4b00-0c4b-11ea-97e2-c0865db5c89f.png">

**Comment by WhistleMaster** [comment]
@tuanha2000vn

**Comment by tuanha2000vn** [comment]
Hi, I've tried the option 1 (beside the icon) and it look ugly especially with long ass status text.

So I've moved them to the bottom, it look nicer. And I don't think make an option for status on top or bottom is a good idea, more option will scare users away because the main idea of this app is Simplicity.

**Comment by tuanha2000vn** [comment]
![image](https://user-images.githubusercontent.com/2765517/69450335-802ae280-0d8f-11ea-87dc-0948819fc6be.png)
The current version look like this, not great but decent I think.

**Comment by WhistleMaster** [comment]
You’re right, everything below is the best option !

Now, just missing the unit (i.e. degrees, lux, %, etc. ) next to the value :-)

**Comment by tuanha2000vn** [comment]
This part not hard I'll do in the final stage

**Comment by WhistleMaster** [comment]
Thanks ! Any news to include the unit :-) ?
