### ISSUE TITLE
iOS App Store only shows English as language

### ISSUE THREAD

**Issue by steckenpferd** [tuanha2000vn/hasskit#45]
![5D884DDC-9BAB-4842-8271-AA5182D0454B](https://user-images.githubusercontent.com/39061622/71475998-2d57a700-27e3-11ea-8943-278a4ae15269.jpeg)

**Comment by tuanha2000vn** [comment]
It's because apple require manual translate every single release change log, so I mark them as English only app.

We can still change language within the app.
![Screenshot_1577371474](https://user-images.githubusercontent.com/2765517/71479873-ec828100-2828-11ea-956b-c03ceb44e898.png)

**Comment by steckenpferd** [comment]
I know you can change but the information would help people in App store that they can change to all this languages

**Comment by tuanha2000vn** [comment]
Fix on next update
