### ISSUE TITLE
Android TV OS - can not be controlled with remote control

### ISSUE THREAD

**Issue by steckenpferd** [tuanha2000vn/hasskit#46]
Hi,

just for fun I installed the hasskit APK on my TV with Android TV 8.0 - I can install and open the App - but navigation with the remote buttons, up, down, left, right and ok is not possible at all. If that would be possible and the buttons would be like "tabs" than it could be used for monitoring.

**Comment by tuanha2000vn** [comment]
lol that fun, let my try install on my Mibox, I'm curious how it will look like :D

**Comment by steckenpferd** [comment]
Did you test it on the Mi Box - how was it?

**Comment by tuanha2000vn** [comment]
Sorry I havent :D

**Comment by tuanha2000vn** [comment]
It’s too much work for android TV and the app don’t make to support this platform. Close for now.
