### ISSUE TITLE
Unable to run/build the app with Flutter 1.12.13

### ISSUE THREAD

**Issue by sherzberg** [tuanha2000vn/hasskit#48]
I'm very new to Flutter dev so not sure exactly where the issues is, but I recently installed flutter on my dev box and am getting this error when trying to run the app on an emulator after checking out this repo (git sha 3fcafd1ecf5fc523eeefb70bb1662ed323275e8f):

```
Finished with error: [!] Your app is using an unsupported Gradle project. To fix this problem, create a new project by running `flutter create -t app <app-directory>` and then move the dart code, assets and pubspec.yaml to the new project.
```

I can try out what the message says, but curious if maybe I just need to install a different version of the flutter sdk?

```
$ flutter doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /opt/flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
```

**Comment by tuanha2000vn** [comment]
Please check gitignore for file that not included in the reposity for security reason and replace by your own (firebase api, google map api...)

Also I use flutter beta.

For detail, ask tyre, he know how to set it up.
