### ISSUE TITLE
UI Improvement suggestions

### ISSUE THREAD

**Issue by skynet01** [tuanha2000vn/hasskit#5]
First of all, thank you for writing this app. It's sooooo much easier to get this going then the real home assistant. I had the app running and rooms laid out in under a minute. I didn't have to plan how things will look and figure out what kind of cards I want to use which is what I have to do with Lovelace.  

There are a few UI suggestions that I have that I believe will improve user experience a lot. There is a lot of unused space at the top and bottom. And both places have settings icons. Settings is something that's not used often, once you set it up you are done. 

The top area can be used to display other sensors like if people are home etc. Would be nice if you can rename the rows too. For the bottom, it would be great to be able to define favorite screens, so for me it could be cameras views or security. 

![IMG_4995428F4066-1](https://user-images.githubusercontent.com/8117544/69368837-3f3cac00-0c71-11ea-8f56-d45849650813.jpeg)

Here is a quick mockup proposing changes. You can remove settings cog all together and have it show up as a link when someone scrolls all the way to the bottom. 
![Screen Shot 2019-11-21 at 3 07 08 PM](https://user-images.githubusercontent.com/8117544/69368925-6b582d00-0c71-11ea-81d9-ddf64acf7cc3.jpg)

I also made the whole tile a different color so you can easily spot which ones are active if you have many of them on the screen.

**Bonus**: Have an option to create a page with everything active views:
I've been using home assistant for more than a year and the majority of the time I want something turned off quickly. It would be great to have a row (maybe an option to add to the screen) or a dedicated screen that shows everything that's running. It's very handy since if you have many devices you can quickly glance at what's running (Ex: if you leave the house etc)

These are just ideas and suggestions, it's a great app. Keep up the great work!

**Comment by tuanha2000vn** [comment]
Hi https://github.com/skynet01

Thank for taking time written a detail suggestion, not everyone can do it.

![image](https://user-images.githubusercontent.com/2765517/69449565-caab5f80-0d8d-11ea-935f-f8b6067feacb.png)
For the top UI, it normally look like this


![image](https://user-images.githubusercontent.com/2765517/69449589-d7c84e80-0d8d-11ea-9f58-af37e06f5f7e.png)
But when scroll up it look like this

So there's not really too much space left, I've tried add a few element, like a icon for Humidity and it look uglier.

I'll try later on that issue.

**Comment by tuanha2000vn** [comment]
The next version will have a display on top with status like

2 lights are on, 4 switch are on and click on them will turn them off...

For row renaming, I'm not sure it's really needed or will add another level of complication to the app that what I really want to avoid.

Few people message me why the Air Con can only turn on/off (they don't know long click can open detail setting @@)... So I really want the app as simple as possible.

**Comment by skynet01** [comment]
Nice, I agree it should be as simple as possible. Maybe you are right about not having text in the bars. 

My main point was about having 2 settings buttons, one at the top one at the bottom. They are used only during setup stage and and then are rearly used again

**Comment by tuanha2000vn** [comment]
Hi man, I think Ive made few improvement next update:

![image](https://user-images.githubusercontent.com/2765517/69476305-ffa9c780-0e0a-11ea-9522-9e4c39679431.png)
Now all running entities will create a red alert on the top right bell

**Comment by tuanha2000vn** [comment]
![image](https://user-images.githubusercontent.com/2765517/69476315-1ea85980-0e0b-11ea-8749-cb4208d1d75b.png)
Clicking on it will let you turn it off

**Comment by tuanha2000vn** [comment]
Currently any entities of these class will appear, I'll make option to it later, like only turn on notif if lock is openned...
```
  List<Entity> get entitiesStatusRunning {
    List<Entity> entities = gd.entities.values
        .where((e) =>
            e.isStateOn &&
            (e.entityId.contains("light.") ||
                e.entityId.contains("switch.") ||
                e.entityId.contains("cover.") ||
                e.entityId.contains("lock.") ||
                e.entityId.contains("fan.") ||
                e.entityId.contains("climate.")))
        .toList();

    return entities;
  }
```

**Comment by tuanha2000vn** [comment]
It's not pretty yet but consider the previous alpha version, it still an improvement haha

![image](https://user-images.githubusercontent.com/2765517/69476354-8d85b280-0e0b-11ea-9893-024d6a3385d6.png)
Look at the previous alpha, I got no idea what I'm doing

**Comment by skynet01** [comment]
Looks nice, would be awesome to modify it. As people have many items that should be on at all times. Or have this as an option. Not sure if alert icon is accurate since it’s not really an alert, just running devices. What about making it one of the tabs in the bottom row? Again these are just suggestions you should make it how you want since it’s your app :)

**Comment by tuanha2000vn** [comment]
I think it should be on top row because it some kind of top priority. Yeah it's not an alert but I have trouble finding the best icon for it.

Can you suggest some icon from this library?

https://materialdesignicons.com/

**Comment by tuanha2000vn** [comment]
![untitled](https://user-images.githubusercontent.com/2765517/69490982-91740c00-0ec1-11ea-80ed-d915812fda5c.gif)

The notification of Active Devices is now selectable invidually, we are getting closer to what we need.

**Comment by skynet01** [comment]
> I think it should be on top row because it some kind of top priority. Yeah it's not an alert but I have trouble finding the best icon for it.
> 
> Can you suggest some icon from this library?
> 
> https://materialdesignicons.com/

You can do something like:
mdi-information
or
mdi-toggle-switch  (basically it shows active switches)

**Comment by tuanha2000vn** [comment]
![untitled](https://user-images.githubusercontent.com/2765517/69684370-06765a00-10eb-11ea-9f67-4667beb14465.gif)

Click on the bell button already show/hide the running device. Add more will be a bit redundant?

**Comment by OptimusGREEN** [comment]
Great work.

I like the idea of being able to change the section numbers to names of my choosing.

**Comment by WhistleMaster** [comment]
The new design does not cut correctly long entity name:

![Untitled](https://user-images.githubusercontent.com/1544568/69807057-a06dfd80-11e4-11ea-8adf-32268500fb31.png)

I guess it should display "Brightnes..." instead of "Brightness", with the "s" on the next line, even if the previous design was better to display long entity name :-P

**Comment by tuanha2000vn** [comment]
Apple don't like HassKit use square shape because they look too much like HomeKit so I have to change to Rectangular... 

As the design use 2 line for Entity Name and 2 line for status, that may result in some ugly line wrap unfortunately.

**Comment by tuanha2000vn** [comment]
![Screenshot_1575904956](https://user-images.githubusercontent.com/2765517/70451481-05c0c900-1ad8-11ea-8bf9-19684ba41988.png)

Been a long way and I'm quite happy with the way App look and feel. And now we suport iPad/Tablet.

**Comment by iantrich** [comment]
changes look nice
