### ISSUE TITLE
FAN mode missing

### ISSUE THREAD

**Issue by A320Peter** [tuanha2000vn/hasskit#50]
I have a Xiaomi Air Purifier connected to HA by the `xiaomi_miio` integration. Home Assistant shows it as `fan` with 3 modes: `auto, silent, favorite`. When I open the device in HassKit (latest iOS app) it shows me a yellow vertical bar with 3 modes and the bottom one is selected. It is labeled as `Auto`. 

![IMG_7559](https://user-images.githubusercontent.com/14132653/71560448-5dfd4200-2a6a-11ea-8505-33369914ea1a.jpg)

If I move the slider to the middle range it becomes `Silent` and if I pull it up to the top it shows `Favorite`. The mode on the device changes accordingly. However after the first interaction the bottom bar becomes the `Off` state so I can never return to `Auto` mode. The bar is now acting from bottom to the top in the following order: `Off, Silent, Favorite`. 

![IMG_7560](https://user-images.githubusercontent.com/14132653/71560454-6d7c8b00-2a6a-11ea-9a36-b7a138bc9aa3.jpg)

The `Auto` mode is not available anymore. If I change back the mode to `Auto` via Home Assistant or in Xiaomi Application then HassKit also adopts the state to `Auto` after a couple of seconds.

**Comment by tuanha2000vn** [comment]
Can you send as much info about the fan as you can. I don't have it so there must be something missing...

**Comment by tuanha2000vn** [comment]
I think I've fixed that issue as well.

**Comment by tuanha2000vn** [comment]
User report issue fixed
