### ISSUE TITLE
Not connecting with HTTPS if certificate is invalid

### ISSUE THREAD

**Issue by A320Peter** [tuanha2000vn/hasskit#51]
I access Home Assistant by HTTPS with a domain `https://xxxx.duckdns.org:8123` which works perfectly in HassKit. When I am at home (and on my local smart home screen) I prefer to use the local LAN address in order not to loose the connection with the server if internet breaks. If I open HA lovelace at `192.168.1.xxx:8123` it works without problem except the browser rises a certificate issue. 

On the latest iOS HassKit app the connection never establishes with this local address, it just keeps saying ‘connecting to...’.

**Comment by A320Peter** [comment]
I access Home Assistant by HTTPS with a domain `https://xxxx.duckdns.org` which works perfectly in HassKit. When I am at home (and on my local smart home screen) I prefer to use the local LAN address in order not to loose the connection with the server if internet breaks. If I open HA lovelace at `192.168.1.xxx:8123` it works without problem except the browser rises a certificate issue. 

However in HassKit the connection never establishes with this local address, it just keeps saying ‘connecting to...’.

**Comment by tuanha2000vn** [comment]
The app use this websocket package to connect to server and the package does not support invalid certificate.

https://pub.dev/packages/web_socket_channel

Let me do some research about the package to know how and when the invalid certificate will get supported.

**Comment by alberto756-90** [comment]
> I access Home Assistant by HTTPS with a domain `https://xxxx.duckdns.org:8123` which works perfectly in HassKit. When I am at home (and on my local smart home screen) I prefer to use the local LAN address in order not to loose the connection with the server if internet breaks. If I open HA lovelace at `192.168.1.xxx:8123` it works without problem except the browser rises a certificate issue.
> 
> On the latest iOS HassKit app the connection never establishes with this local address, it just keeps saying ‘connecting to...’.

**Comment by alberto756-90** [comment]
Qaaa

**Comment by tuanha2000vn** [comment]
I've open the issue 4 days ago, I guess it's holiday and the devs taking a break

https://github.com/dart-lang/web_socket_channel/issues/92

**Comment by tuanha2000vn** [comment]
Look like it’s not possible at the moment according to the author of this package reply to my issue report. Close for more.
