### ISSUE TITLE
IKEA window blind has odd indication

### ISSUE THREAD

**Issue by A320Peter** [tuanha2000vn/hasskit#52]
In HassKit the `IKEA Fyrtur` blind (connected via Zigbee with Deconz) has an odd behavior. It goes precisely to the selected position but the slider has a strange indication. After adjusting the blind the indication always jumps to zero and only goes back to open position if the blind is fully open. I have attached a GIF for easier understanding:

![RPReplay_Final1577648232](https://user-images.githubusercontent.com/14132653/71561812-e801d680-2a7b-11ea-80b4-c7633311f770.gif)

**Comment by tuanha2000vn** [comment]
I think there is a bug updating status, will fix it next update.

**Comment by tuanha2000vn** [comment]
User report issue fixed
