### ISSUE TITLE
3.6.3, 3.6.4 temperature graph not showing

### ISSUE THREAD

**Issue by kirichkov** [tuanha2000vn/hasskit#53]
Since upgrading to 3.6.4 the temperature graph doesn't work on iOS. I still have 3.5.5 on my iPad and there it works as expected. Instead of the graph I get the text `has no data available 0`. I also got sometimes data that was related to a different entity, I've viewed previously (motion sensor).

P.S. It appears this error is not iOS specific. On Android (version 3.6.3.) I get the same error and no graph.

**Comment by kirichkov** [comment]
After doing some sniffing and digging in the code, it appears that hasskit is generating a bad URL, so HASS responds with `400:  Bad request`

I tracked the issue to the timestamp format. On my device I get the following:

    GET /api/history/period/2019-12-28T23:59:59EET:00?end_time=2019-12-30T23%3A59%3A59EET%3A00&filter_entity_id=sensor.temperature

I think the issue is with adding the timezone name and `:00` :
https://github.com/tuanha2000vn/hasskit/blob/8c9e3e5af2a6bd7d7e64e60bb0076d1c811dc7df/lib/view/entitycontrol/entity_control_sensor.dart#L141

Same goes for the `end_time` query param: https://github.com/tuanha2000vn/hasskit/blob/8c9e3e5af2a6bd7d7e64e60bb0076d1c811dc7df/lib/view/entitycontrol/entity_control_sensor.dart#L145

I think if you remove the above lines the issue will be fixed. Any idea why you added them? Perhaps it's not that simple solution.

**Comment by kirichkov** [comment]
I think for some reason on your dev/test devices `timeZoneName` is returning the hour offset, but I think the correct way to do this is using [timeZoneOffset](https://api.dartlang.org/stable/2.7.0/dart-core/DateTime/timeZoneOffset.html):

    startPeriodString = startPeriodString + DateTime.now().timeZoneOffset; 

    endPeriodString = endPeriodString + DateTime.now().timeZoneOffset;

**Comment by tuanha2000vn** [comment]
Thank you for finding the issue, I will l fix next release
