### ISSUE TITLE
Thermostat now goes up tenths of a degree

### ISSUE THREAD

**Issue by scfigg** [tuanha2000vn/hasskit#57]
First release would allow me to change the thermostat 1 degree F. Now, it goes to tenth degrees (70.1, 70.2, 70.3 etc) instead of 70, 71, 72. Super annoying because my thermostat doesn't support that and makes changing temperatures hard.

**Comment by tuanha2000vn** [comment]
Let me check

**Comment by tuanha2000vn** [comment]
I've fixed on newest release, will be on the store 1-2 day

https://github.com/tuanha2000vn/hasskit/releases/tag/3.7

**Comment by scfigg** [comment]
I'm on 3.8 now and it still goes up by 0.1 degree.

**Comment by tuanha2000vn** [comment]
Can you test this 3.9 release and let me know how the climate behave?

https://github.com/tuanha2000vn/hasskit/releases/tag/3.9

**Comment by scfigg** [comment]
Perfect! Working great now. Thanks for your super fast response and fixing
the issue, and all the great features you're adding.
