### ISSUE TITLE
[FEATURE REQUEST] Search Icons

### ISSUE THREAD

**Issue by aptonline** [tuanha2000vn/hasskit#59]
Having the ability to search for icons based on name would be super useful and speed up entity creation.

**Comment by tuanha2000vn** [comment]
I've tried to support 25k icon from https://materialdesignicons.com/ into the app and it take 5 min to start up so this feature aborted :D 

Try search for icon name in their website instead, it's fast and convenience

https://materialdesignicons.com/

**Comment by aptonline** [comment]
I know I can search for icons from the website but it’s when I want to quickly add a specific icon to an entity for the list chosen that a search would be useful. Maybe the word filter is more appropriate in this case.

**Comment by tuanha2000vn** [comment]
Mission completed
