### ISSUE TITLE
FR: Friendly state display for binary sensors

### ISSUE THREAD

**Issue by iantrich** [tuanha2000vn/hasskit#6]
You can find the current translations in the polymer repo, broken out by device class:

https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/translations/en.json#L81

**Comment by tuanha2000vn** [comment]
Where did you find that code? I've party  fix is here:

String stateString(String deviceClass, bool isStateOn) {
  log.d("stateString deviceClass $deviceClass");
  if (deviceClass.contains("garage_door") ||
      deviceClass.contains("door") ||
      deviceClass.contains("lock") ||
      deviceClass.contains("opening") ||
      deviceClass.contains("window")) {
    if (isStateOn) {
      return "open";
    }
    return "closed";
  }

  if (isStateOn) {
    return "on";
  }
  return "off";
}

**Comment by iantrich** [comment]
I've been working on the polymer repo (Home Assistant frontend) for over a year, so I know where most things are 😜

**Comment by tuanha2000vn** [comment]
Added, thank

**Comment by iantrich** [comment]
🎉
