### ISSUE TITLE
[BUG] Renaming group name 4 doesn't change in settings

### ISSUE THREAD

**Issue by aptonline** [tuanha2000vn/hasskit#62]
If I change the group name 4 in settings it does change in the front end but when I enter settings again for that room it shows the name of group name 3 and not the correct name.

For example I have the following group names: General,Switches,Cameras,Plants but if I change Plants to Other in the settings is displays correctly in the front end but when I go back into settings it shows General,Switches, Cameras, Cameras.

**Comment by tuanha2000vn** [comment]
Thank you, fixed on next update
