### ISSUE TITLE
Thermostat in 3.8 still goes up by 0.1

### ISSUE THREAD

**Issue by scfigg** [tuanha2000vn/hasskit#63]
I'm on 3.8 now and it still goes up by 0.1 degree.

_Originally posted by @scfigg in https://github.com/tuanha2000vn/hasskit/issues/57#issuecomment-570819826_

**Comment by tuanha2000vn** [comment]
if (gd.entities[entityId].targetTempStep == 1 ||
              gd.entities[entityId].unitOfMeasurement == "°F") {
            return ' ${value.toInt()}˚';
          } else if (gd.entities[entityId].targetTempStep == 0.5) {
            return ' ${gd.roundTo05(value)}˚';
          } else {
            return ' ${value.toStringAsFixed(1)}˚';
          }

If your climate is °F or support temp step 1 then it will jump by 1 degree...

What is your climate config in Home Assistant look like?

**Comment by tuanha2000vn** [comment]
Initially I only support 1 degree jump then a guy ask for 0.1 because his climate support it.

**Comment by scfigg** [comment]
Looks like it's working now. Is there any way to set a preference to go back to the previous Wait it worked? It went up by one full degree each number. This makes it a lot more intricate and I feel like I need to be a lot more precise when moving. AKA smaller adjustments are required for the thermostat and it makes it a lot more tedious to change the temperature for Fahrenheit.

**Comment by scfigg** [comment]
Would there be any way to have an option in preferences to select which way
it works? It's quite tedious for anyone in the US pretty much.

**Comment by tuanha2000vn** [comment]
Next update I'll set 0.5 and 1 degree adjustment for Celsius and 1 degree  adjusment step for fahrenheit

**Comment by scfigg** [comment]
Awesome, thank you so much! I appreciate all of the awesome quick updates.
