### ISSUE TITLE
FR: alarm panel control

### ISSUE THREAD

**Issue by iantrich** [tuanha2000vn/hasskit#7]
Ability to arm/disarm the alarm panel

**Comment by tuanha2000vn** [comment]
OK, let me fix some stuff and learn how the Alarm in HA work.

**Comment by iantrich** [comment]
We'll just need a keypad for input and then call the appropriate service. This should show you most of what you need, I believe:
https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/data/alarm_control_panel.ts

**Comment by Tyre88** [comment]
#8

**Comment by tuanha2000vn** [comment]
![image](https://user-images.githubusercontent.com/2765517/69500008-0b3fe000-0f2a-11ea-8a46-04a26776d360.png)
Thak so much guy, implement the color so it look like this

**Comment by iantrich** [comment]
🎉

**Comment by tuanha2000vn** [comment]
Some minor improvement if needed. Consider is closed.
