### ISSUE TITLE
Hasskit background location update drains the battery

### ISSUE THREAD

**Issue by dtx360** [tuanha2000vn/hasskit#71]
Greetings, turned on the new background location update with the default settings. Seems it drained 43% of the battery during the last 24 hours, see attaches image. Is this expected? I don’t see this kind of usage with the home assistant companion 2.0.

![264D381D-CA9B-4E3E-8121-250EEE9ECC73](https://user-images.githubusercontent.com/54236204/72499194-71adf400-3831-11ea-8bdb-4531222eeef4.png)

![1493AE09-2AB6-4DB9-B192-2CE596F4552D](https://user-images.githubusercontent.com/54236204/72498986-f77d6f80-3830-11ea-94dc-668d60588cbd.png)

**Comment by tuanha2000vn** [comment]
Thank, the location tracking still in it early development, I'll try to optimize it.

**Comment by tuanha2000vn** [comment]
What the app are you using to track battery?

**Comment by dtx360** [comment]
It’s the apple ios built-in tracker available at settings:battery.

**Comment by dtx360** [comment]
Hi, tried the latest version today and still 45-50% usage of total battery capacity :(

Regards Per

**Comment by tuanha2000vn** [comment]
Hi, I'm in middle of completely rewrite the location tracking pad, please give us some more time.

And yes, app eat too much battery on my phone as well.

**Comment by tuanha2000vn** [comment]
Remove location tracking code for now as it's not good enough.
