### ISSUE TITLE
[Feature Request] Add support for water_heater entity

### ISSUE THREAD

**Issue by Kvasenok** [tuanha2000vn/hasskit#73]
Now pressing a water_heater entity just opens up "entity menu" with a huge icon. The entity itself is similar to climate entities as it has current and set temperature values and a mode selector.

**Comment by tuanha2000vn** [comment]
Do you have a template or something that can create a virtual water heater? I need something like that to start coding.

**Comment by Kvasenok** [comment]
@tuanha2000vn unfortunately, no. I don't think it's possible to create a template water heater. All I can provide are the dev docs: https://developers.home-assistant.io/docs/en/entity_water_heater.html
Also I can make a few screenshots of my water heater in HA, if it helps.

**Comment by tuanha2000vn** [comment]
Here we go
https://github.com/tuanha2000vn/hasskit/releases/tag/4.3
