### ISSUE TITLE
Change "Tile" name

### ISSUE THREAD

**Issue by pasoad** [tuanha2000vn/hasskit#74]
Hello!

First of all, thanks for this great app. It's a very WAF UI 😁.

Can we change a tile name to not have something like this ? I just would like to see the valves place

![Screenshot_20200128_111143_com thhkstudio hasskit](https://user-images.githubusercontent.com/46829490/73256413-22b57680-41c2-11ea-9230-a0226a761991.png)

**Comment by tuanha2000vn** [comment]
![untitled](https://user-images.githubusercontent.com/2765517/73274496-3a1f4e80-4218-11ea-953f-40b73254efdd.gif)

Long Press the title to open the detail setting.
Click the cogwheel on top-right
Change the name

**Comment by pasoad** [comment]
Thanks a lot :)
