### ISSUE TITLE
Light - groups

### ISSUE THREAD

**Issue by Tyre88** [tuanha2000vn/hasskit#80]
Make so if a group only contains lights act like a light switch as the same as rooms from HUE.

**Comment by tuanha2000vn** [comment]
Can you explain in detail?

**Comment by Tyre88** [comment]
At the moment when you click on a group it opens a slider for turning on and off the grp. 
What i want is that if you click on a grp with only lights in then it should toggle the whole groups lights on and off on single click and on long click you should get the light options with dimming and color handling.

**Comment by Kvasenok** [comment]
You can create a light group instead of a normal group in HA and will act as a single light entity with all the features.
https://www.home-assistant.io/integrations/light.group/

**Comment by Tyre88** [comment]
Thanks @Kvasenok that's exactly what i wanted!
