### ISSUE TITLE
Auth error from APNS or Web Push Service with Ipad and IOS HASSKIT

### ISSUE THREAD

**Issue by faspina** [tuanha2000vn/hasskit#90]
This is a new problem, I have node red automation that send notification to HASSKIT on both iPad and iPhone. 

I am not getting a 

Auth error from APNS or Web Push Service

Push error

I deleted the integration in HA ,  and regestered hasskit to get a new notify device.  

Any ideas?

**Comment by tuanha2000vn** [comment]
Please use Home-Dashboard, this app no longer maintained
